version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_library

  env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - pgdata_library:/var/lib/postgresql/data
    networks:
      - devops_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d library"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: serzhan/online-library:1.0
    container_name: online_library_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      APP_PORT: ${APP_PORT}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - devops_net

volumes:
  pgdata_library:

networks:
  devops_net:
    driver: bridge
